  app-mqtt-export_APP_INDEX:
    command:
      - /app-service-configurable
      - --registry
      - -cp=keeper.http://edgex-core-keeper:59890
    container_name: edgex-app-mqtt-export_APP_INDEX
    depends_on:
      core-common-config-bootstrapper:
        condition: service_started
        required: true
      core-keeper:
        condition: service_started
        required: true
      core-metadata:
        condition: service_started
        required: true
      security-bootstrapper:
        condition: service_started
        required: true
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_PROFILE: mqtt-export_APP_INDEX
      EDGEX_SECURITY_SECRET_STORE: "true"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      SECRETSTORE_HOST: edgex-secret-store
      SERVICE_HOST: edgex-app-mqtt-export_APP_INDEX
      SERVICE_STARTUPMSG: "app-mqtt-export_APP_INDEX has Started"
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-postgres
      STAGEGATE_DATABASE_PORT: "5432"
      STAGEGATE_DATABASE_READYPORT: "5432"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-keeper
      STAGEGATE_REGISTRY_PORT: "59890"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      WRITABLE_PIPELINE_EXECUTIONORDER: "MQTTExport"
      WRITABLE_PIPELINE_FUNCTIONS_MQTTEXPORT_PARAMETERS_BROKERADDRESS: BROKER_ADDRESS
      WRITABLE_PIPELINE_FUNCTIONS_MQTTEXPORT_PARAMETERS_TOPIC: "edgex/events/device/PROFILE_NAME"
      WRITABLE_PIPELINE_FUNCTIONS_MQTTEXPORT_PARAMETERS_CLIENTID: "MQTT-Export_APP_INDEX"
      MESSAGEBUS_OPTIONAL_CLIENTID: "app-mqtt-export_APP_INDEX"
      TRIGGER_SUBSCRIBETOPICS: "events/device/SERVICE_NAME/PROFILE_NAME/#"
    hostname: edgex-app-mqtt-export_APP_INDEX
    image: nexus3.edgexfoundry.org:10004/app-service-configurable${USE_ARM64}:latest
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: edgex-init
        target: /edgex-init
        read_only: true
        volume: {}
      - type: bind
        source: /tmp/edgex/secrets/app-mqtt-export_APP_INDEX
        target: /tmp/edgex/secrets/app-mqtt-export_APP_INDEX
        read_only: true
        bind:
          selinux: z
          create_host_path: true
      - type: bind
        source: ${WORK_DIR}/app_dir
        target: /res
        read_only: true
        bind:
          create_host_path: true
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
