#############################################
# Export Server
#############################################
services:
  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    restart: always
    hostname: telegraf
    user: telegraf:${HOST_DOCKER_GROUP_ID}
    networks:
      edgex-network: null
    volumes:
      - ${WORK_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/sysstat/sadc:/usr/lib/sysstat/sadc:ro
      - /usr/bin/sadf:/usr/bin/sadf:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  device-modbus:
    command:
      - -cp=keeper.http://edgex-core-keeper:59890
      - --registry
    container_name: edgex-device-modbus
    depends_on:
      core-common-config-bootstrapper:
        condition: service_started
        required: true
      core-keeper:
        condition: service_started
        required: true
      core-metadata:
        condition: service_started
        required: true
    environment:
      EDGEX_MSG_BASE64_PAYLOAD: "true"
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-device-modbus
      DEVICE_PROFILESDIR: /res/edgex/profiles
      DEVICE_DEVICESDIR: /res/edgex/devices
    hostname: edgex-device-modbus
    image: nexus3.edgexfoundry.org:10004/device-modbus${USE_ARM64}:latest
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59901
        published: "59901"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: ${WORK_DIR}/simulators
        target: /res/edgex
        read_only: true
        bind:
          create_host_path: true

  core-metadata:
    environment:
      SERVICE_REQUESTTIMEOUT: "30s"
